name: ML311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - captum==0.8.0
      - duckdb==1.4.1
      - joblib==1.5.2
      - matplotlib==3.10.8
      - numpy==1.26.4
      - pandas==2.3.3
      - pyarrow==22.0.0
      - PyYAML==6.0.3
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - tabulate==0.9.0
      - torch==2.11.0.dev20251216+cu128
      - tqdm==4.67.1
      - xgboost==3.1.3

